### ISSUE TITLE
Toogle Render Mode

### ISSUE THREAD

**Issue by joewashear007** [patrick330602/Fcus-UWP#5]
Hello,

Is it possible to make a toggle render mode for the application. As you can see in the picture, When the app is not full screen, you can't see the render content. If this feature is already implemented, then I would recommend change the UI to make it easy to find.

Thanks,
Joe

<img width="864" alt="sketch 1" src="https://cloud.githubusercontent.com/assets/3577785/22621769/33aac9ea-eaf9-11e6-9d55-05e805620e39.png">

**Comment by patrick330602** [comment]
Thanks for your feedback. I will be working on this bug soon.

**Comment by patrick330602** [comment]
This issue is fixed in the latest commit, so I will close this issue
