### ISSUE TITLE
微软官方的类库最近支持了MarkdownTextBlock，有兴趣换用吗

### ISSUE THREAD

**Issue by yinyue200** [patrick330602/Fcus-UWP#8]
https://github.com/Microsoft/UWPCommunityToolkit/tree/dev/Microsoft.Toolkit.Uwp.UI.Controls/MarkdownTextBlock
可能不如现在的HTML5版本，只是个新的选择

**Comment by yinyue200** [comment]
最大的问题好像是官方的没有markdown代码着色。。。。

**Comment by patrick330602** [comment]
我现在考虑“关于”部分用MarkdownTextBlock写，output部分更新一下样式表（最接近GitHub的效果）

**Comment by yinyue200** [comment]
那很好，期待 @patrick330602

**Comment by patrick330602** [comment]
@BOT-Man-JL 嗯，我现在用的是markdown-it, 我倒是想用MarkdownTextBlock做关于界面😀

**Comment by yinyue200** [comment]
@BOT-Man-JL 有没有考虑过下载MarkdownTextBlock的源码然后手动改

**Comment by patrick330602** [comment]
关于界面已经完成，所以这个issue我关了（滑稽
